#spring.application.name=pharmacy
#
#server.port=8080
#
## MySQL datasource configuration
##spring.datasource.url=jdbc:mysql://localhost:3306/practice
##spring.datasource.username=root
##spring.datasource.password=root
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/practice}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## JPA / Hibernate config
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
# 1. Project Name
spring.application.name=pharmacy

# 2. Port Configuration (Railway needs this to run online)
server.port=${PORT:8080}

# 3. Database Connection (Using your Railway MySQL details)
#spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:28788/railway
spring.datasource.url=jdbc:mysql://localhost:3306/practice
spring.datasource.username=root
#spring.datasource.password=GYqgrCcbsrxKMQrekDFasdHYLTsTuKmC
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate Config (Tables automatically create ho jayenge)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 5. Connection Timeout Fix
spring.datasource.hikari.initialization-fail-timeout=0